[tool.ruff]
target-version = "py310"
line-length = 100
src = [
  "agents",
  "backend",
  "config",
  "tests",
  "run.py",
]
extend-exclude = [
  "venv",
  "data",
  "logs",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = [
  "E501",  # line length handled by formatter / long strings
  "F401",  # allow imported but unused (API schemas, __init__ convenience)
]

